--
-- workflow-service — schéma initial, relevé du schéma en service au 7 août 2026.
--
-- Moteur de circuits : circuits, étapes, transitions, instances, notifications.
--
-- Ce script est le POINT DE DÉPART de l'historique de migration : il décrit le schéma tel que
-- « ddl-auto: update » l'avait construit. Une base déjà en service est marquée « v1 » sans que ce
-- script y soit rejoué (baseline-on-migrate) ; une base vide le reçoit intégralement. Les deux
-- suivent ensuite la même suite de migrations, ce qui est tout l'objet de Flyway.
--
-- NE JAMAIS MODIFIER un script déjà appliqué : Flyway en vérifie l'empreinte et refuserait de
-- démarrer. Toute correction du schéma passe par un nouveau V<n+1>__....sql.
--

--
--

SET default_table_access_method = heap;

--
-- Name: workflow; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.workflow (
    id uuid NOT NULL,
    created_at timestamp(6) without time zone,
    created_by_id character varying(255),
    current_user_email character varying(255),
    current_user_structure character varying(255),
    current_user_full_name character varying(255),
    direction_id uuid,
    update_at timestamp(6) without time zone,
    update_by_id character varying(255),
    actif boolean DEFAULT true NOT NULL,
    cible_id character varying(100),
    description character varying(255),
    nom character varying(255) NOT NULL,
    resource_type character varying(255) NOT NULL
);

--
-- Name: workflow_email_template; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.workflow_email_template (
    id uuid NOT NULL,
    created_at timestamp(6) without time zone,
    created_by_id character varying(255),
    current_user_email character varying(255),
    current_user_structure character varying(255),
    current_user_full_name character varying(255),
    direction_id uuid,
    update_at timestamp(6) without time zone,
    update_by_id character varying(255),
    body text NOT NULL,
    code character varying(100) NOT NULL,
    description character varying(500),
    subject character varying(255) NOT NULL
);

--
-- Name: workflow_field_value; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.workflow_field_value (
    id bigint NOT NULL,
    field_code character varying(255) NOT NULL,
    field_label character varying(255),
    field_name character varying(255),
    value text,
    history_id bigint NOT NULL
);

--
-- Name: workflow_field_value_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.workflow_field_value ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.workflow_field_value_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: workflow_notification; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.workflow_notification (
    id uuid NOT NULL,
    canal character varying(255) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    derniere_erreur character varying(1000),
    payload text NOT NULL,
    prochaine_tentative_at timestamp(6) without time zone,
    remise_at timestamp(6) without time zone,
    resource_id character varying(255) NOT NULL,
    resource_type character varying(255) NOT NULL,
    statut character varying(255) NOT NULL,
    tentatives integer NOT NULL,
    CONSTRAINT workflow_notification_canal_check CHECK (((canal)::text = ANY ((ARRAY['WEBHOOK'::character varying, 'EMAIL'::character varying])::text[]))),
    CONSTRAINT workflow_notification_statut_check CHECK (((statut)::text = ANY ((ARRAY['A_REMETTRE'::character varying, 'EN_COURS_DE_REMISE'::character varying, 'REMISE'::character varying, 'ABANDONNEE'::character varying])::text[])))
);

--
-- Name: workflow_step; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.workflow_step (
    id bigint NOT NULL,
    champ_titulaire character varying(255),
    code character varying(255) NOT NULL,
    description character varying(255),
    email_template_code character varying(255),
    etat_traitement character varying(255),
    nom_etape character varying(255) NOT NULL,
    responsable_role character varying(255),
    step_order integer NOT NULL,
    step_template_id uuid,
    workflow_id uuid NOT NULL
);

--
-- Name: workflow_step_field; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.workflow_step_field (
    id bigint NOT NULL,
    action_code character varying(60),
    decision character varying(255),
    field_label character varying(255) NOT NULL,
    field_name character varying(255) NOT NULL,
    is_required boolean NOT NULL,
    options text,
    type character varying(255) NOT NULL,
    step_id bigint NOT NULL,
    CONSTRAINT workflow_step_field_decision_check CHECK (((decision)::text = ANY ((ARRAY['APPROUVE'::character varying, 'REJETE'::character varying])::text[]))),
    CONSTRAINT workflow_step_field_type_check CHECK (((type)::text = ANY ((ARRAY['TEXT'::character varying, 'NUMERIC'::character varying, 'SELECT'::character varying, 'FILE'::character varying, 'DATE'::character varying])::text[])))
);

--
-- Name: workflow_step_field_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.workflow_step_field ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.workflow_step_field_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: workflow_step_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.workflow_step ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.workflow_step_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: workflow_transition; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.workflow_transition (
    id bigint NOT NULL,
    code character varying(60),
    condition_libelle character varying(500),
    condition_requise character varying(255),
    decision character varying(255) NOT NULL,
    icon character varying(255),
    label character varying(255),
    required_role character varying(255),
    severity character varying(20),
    terminal boolean NOT NULL,
    from_step_id bigint NOT NULL,
    to_step_id bigint,
    CONSTRAINT workflow_transition_decision_check CHECK (((decision)::text = ANY ((ARRAY['APPROUVE'::character varying, 'REJETE'::character varying])::text[]))),
    CONSTRAINT workflow_transition_severity_check CHECK (((severity)::text = ANY ((ARRAY['PRIMARY'::character varying, 'SECONDARY'::character varying, 'SUCCESS'::character varying, 'INFO'::character varying, 'WARN'::character varying, 'DANGER'::character varying, 'HELP'::character varying, 'CONTRAST'::character varying])::text[])))
);

--
-- Name: workflow_transition_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.workflow_transition ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.workflow_transition_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: workflow_validation_history; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.workflow_validation_history (
    id bigint NOT NULL,
    comments character varying(255),
    decision character varying(255) NOT NULL,
    decision_date timestamp(6) without time zone,
    document_hash character varying(255),
    step_code character varying(255) NOT NULL,
    step_name character varying(255),
    validator_full_name character varying(255),
    validator_user_id character varying(255) NOT NULL,
    validation_instance_id uuid NOT NULL
);

--
-- Name: workflow_validation_history_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.workflow_validation_history ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.workflow_validation_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: workflow_validation_instance; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.workflow_validation_instance (
    id uuid NOT NULL,
    completed_at timestamp(6) without time zone,
    createur_id character varying(255),
    etat_code character varying(255) NOT NULL,
    faits character varying(2000),
    observation character varying(2000),
    resource_id character varying(255) NOT NULL,
    resource_type character varying(255) NOT NULL,
    started_at timestamp(6) without time zone,
    status character varying(255) NOT NULL,
    titulaire_id character varying(255),
    version bigint,
    workflow_code character varying(255) NOT NULL,
    CONSTRAINT workflow_validation_instance_status_check CHECK (((status)::text = ANY ((ARRAY['EN_COURS'::character varying, 'TERMINE'::character varying])::text[])))
);

--
-- Name: workflow_step uk_workflow_step_code; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workflow_step
    ADD CONSTRAINT uk_workflow_step_code UNIQUE (workflow_id, code);

--
-- Name: workflow_transition uk_workflow_transition_from_code; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workflow_transition
    ADD CONSTRAINT uk_workflow_transition_from_code UNIQUE (from_step_id, code);

--
-- Name: workflow_email_template ukgga8nddxj3cgf1oqeyw5xsm3o; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workflow_email_template
    ADD CONSTRAINT ukgga8nddxj3cgf1oqeyw5xsm3o UNIQUE (code);

--
-- Name: workflow_email_template workflow_email_template_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workflow_email_template
    ADD CONSTRAINT workflow_email_template_pkey PRIMARY KEY (id);

--
-- Name: workflow_field_value workflow_field_value_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workflow_field_value
    ADD CONSTRAINT workflow_field_value_pkey PRIMARY KEY (id);

--
-- Name: workflow_notification workflow_notification_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workflow_notification
    ADD CONSTRAINT workflow_notification_pkey PRIMARY KEY (id);

--
-- Name: workflow workflow_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workflow
    ADD CONSTRAINT workflow_pkey PRIMARY KEY (id);

--
-- Name: workflow_step_field workflow_step_field_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workflow_step_field
    ADD CONSTRAINT workflow_step_field_pkey PRIMARY KEY (id);

--
-- Name: workflow_step workflow_step_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workflow_step
    ADD CONSTRAINT workflow_step_pkey PRIMARY KEY (id);

--
-- Name: workflow_transition workflow_transition_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workflow_transition
    ADD CONSTRAINT workflow_transition_pkey PRIMARY KEY (id);

--
-- Name: workflow_validation_history workflow_validation_history_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workflow_validation_history
    ADD CONSTRAINT workflow_validation_history_pkey PRIMARY KEY (id);

--
-- Name: workflow_validation_instance workflow_validation_instance_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workflow_validation_instance
    ADD CONSTRAINT workflow_validation_instance_pkey PRIMARY KEY (id);

--
-- Name: idx_workflow_notification_statut; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_workflow_notification_statut ON public.workflow_notification USING btree (statut, prochaine_tentative_at);

--
-- Name: uk_workflow_famille_cible; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uk_workflow_famille_cible ON public.workflow USING btree (resource_type, cible_id) WHERE ((cible_id IS NOT NULL) AND actif);

--
-- Name: uk_workflow_famille_defaut; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uk_workflow_famille_defaut ON public.workflow USING btree (resource_type) WHERE ((cible_id IS NULL) AND actif);

--
-- Name: workflow_step_field fk836e1tdtobu2di78ryem10qhy; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workflow_step_field
    ADD CONSTRAINT fk836e1tdtobu2di78ryem10qhy FOREIGN KEY (step_id) REFERENCES public.workflow_step(id);

--
-- Name: workflow_field_value fkee25i3uc3atscx1d4n9n8o1od; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workflow_field_value
    ADD CONSTRAINT fkee25i3uc3atscx1d4n9n8o1od FOREIGN KEY (history_id) REFERENCES public.workflow_validation_history(id);

--
-- Name: workflow_validation_history fkr5dj3x2aqps4hqxoxqc3d7ix; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workflow_validation_history
    ADD CONSTRAINT fkr5dj3x2aqps4hqxoxqc3d7ix FOREIGN KEY (validation_instance_id) REFERENCES public.workflow_validation_instance(id);

--
-- Name: workflow_transition fkrbvu1rgn3v7yg62svdry2g135; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workflow_transition
    ADD CONSTRAINT fkrbvu1rgn3v7yg62svdry2g135 FOREIGN KEY (from_step_id) REFERENCES public.workflow_step(id);

--
-- Name: workflow_step fkrs03p6vbs0o5uoxubb0to3dwv; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workflow_step
    ADD CONSTRAINT fkrs03p6vbs0o5uoxubb0to3dwv FOREIGN KEY (workflow_id) REFERENCES public.workflow(id);

--
-- Name: workflow_transition fkt1wn5ysve9nfocrxyyigbe3c7; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workflow_transition
    ADD CONSTRAINT fkt1wn5ysve9nfocrxyyigbe3c7 FOREIGN KEY (to_step_id) REFERENCES public.workflow_step(id);

--
--
