# Étape 1 : Build avec Maven et Java 21
FROM maven:3.9.6-eclipse-temurin-21 AS build
WORKDIR /app

# Copie du pom.xml parent et des sources
COPY . .

# Compilation spécifique du module context
# -pl : project list (on cible contexte)
# -am : also make (on compile les dépendances nécessaires comme le module common s'il existe)
RUN mvn clean package -DskipTests -pl contexte-service -am

# Étape 2 : Image finale légère avec le JRE 21
FROM eclipse-temurin:21-jre-jammy
WORKDIR /app

# On récupère le JAR généré dans l'étape précédente
# Vérifie bien que le dossier s'appelle "context-service" dans ton projet
COPY --from=build /app/contexte-service/target/*.jar contexte-service.jar

EXPOSE 8086

ENTRYPOINT ["java", "-jar", "contexte-service.jar"]