# Étape de Build avec Maven et Java 21
FROM maven:3.9.6-eclipse-temurin-21 AS build
WORKDIR /app
COPY . .
RUN mvn clean package -DskipTests -pl discovery -am

# Étape Finale avec Java 21 (JRE)
FROM eclipse-temurin:21-jre-jammy
WORKDIR /app
COPY --from=build /app/discovery/target/*.jar discovery.jar
EXPOSE 8761
ENTRYPOINT ["java", "-jar", "discovery.jar"]