spring:
  application:
    name: qualiapproche

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/quali
          jwk-set-uri: http://localhost:8080/realms/quali/protocol/openid-connect/certs

  graphql:
    graphiql:
      enabled: false

  datasource:
    hikari:
      auto-commit: true

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  profiles:
    active: @spring.profiles.active@

  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: qualiapproche@gmail.com
    password: quali2023
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        transport:
          protocol: smtp
  admin:
    email: admin@demo.com

frontend:
  url: http://localhost:4200


kc:
  auth:
    realm: quali
    client-id: qualiApproche
    client-secret: zZIvoJmcBNoQsfccNUeEBHnSEj8RuTUT
    scope: openid,offline_access,profile
    token-uri: http://localhost:8080/realms/quali/protocol/openid-connect/token
    issuer-uri: http://localhost:8080/realms/quali
    server-url: http://localhost:8080
    admin-username:

    admin-password: admin

logging:
  level:
    org.springframework.web: error
    gov.bf.dgtcp.ebanking.: debug
    org.hibernate: error
    org: info
    root: info
    sql: info
