spring:
  datasource:
    url: jdbc:postgresql://144.126.135.120:5432/bd_dev_qualiapproche
    driver-class-name: org.postgresql.Driver
    username: user_dev
    password: user_dev_password

#UTILISER EN PRODUCTION
#    url: jdbc:postgresql://144.126.135.120:5432/bd_qualiapproche
#    driver-class-name: org.postgresql.Driver
#    username: super_admin
#    password: super_admin_password
#UTILISER EN PRODUCTION

  jpa:
    show-sql: true

server:
  port: 8086

docs:
  pj:
    directory: C:\Users\l\Desktop\SM\e-banking\PIECES_JOINTES