spring:
  application:
    name: qualiapproche

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://keycloak.horeb.tech/realms/quali
          jwk-set-uri: https://keycloak.horeb.tech/realms/quali/protocol/openid-connect/certs

  graphql:
    graphiql:
      enabled: false

  datasource:
    hikari:
      auto-commit: true

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  profiles:
    active: dev

  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: tachquali@gmail.com
    password: qpkcnamwhjfkundy
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        transport:
          protocol: smtp
  admin:
    email: admin@demo.com

frontend:
  url: http://localhost:4200


#kc:
#  auth:
#    realm: quali
#    client-id: dev_quali
#    client-secret: TsCLTqQhJHqCIaqo2GVw3O96hP9qgjxo
#    scope: openid,offline_access,profile
#    token-uri: https://keycloak.horeb.tech/realms/quali/protocol/openid-connect/token
#    issuer-uri: https://keycloak.horeb.tech/realms/quali
#    server-url: https://keycloak.horeb.tech/
#    admin-username: Horeb
#    admin-password: horeb_password

#UTILISER EN PRODUCTION#######
kc:
  auth:
    realm: quali
    client-id: qualiApproche
    client-secret: U2VSU8hANgcg4lqZq9IFzYU2IMlx8Jgs
    scope: openid,offline_access,profile
    token-uri: https://keycloak.horeb.tech/realms/quali/protocol/openid-connect/token
    issuer-uri: https://keycloak.horeb.tech/realms/quali
    server-url: https://keycloak.horeb.tech/
    admin-username: Horeb
    admin-password: horeb_password
#UTILISER EN PRODUCTION#######

logging:
  level:
    org.springframework.web: error
    gov.bf.dgtcp.ebanking.: debug
    org.hibernate: error
    org: info
    root: info
    sql: info
