server:
  port: 8084

spring:
  application:
    name: referentiel-service
  datasource:
    url: ${DB_URL_REFERENTIEL:jdbc:postgresql://localhost:5433/bd_quali_sira_referentiel}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KC_ISSUER_URI:http://localhost:8080/realms/quali-approche}
      client:
        registration:
          keycloak:
            client-id: ${KC_CLIENT_ID:quali-approche}
            client-secret: ${KC_CLIENT_SECRET:EGBtXZ6hO13LHY8BfFwjkUgdINNtAXeu}
            authorization-grant-type: client_credentials
        provider:
          keycloak:
            token-uri: ${KC_TOKEN_URI:http://localhost:8080/realms/quali/protocol/openid-connect/token}
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:tachquali@gmail.com}
    password: ${MAIL_PASSWORD:qpkcnamwhjfkundy}
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
# ===============================
# Gestion des documents (PJ)
# ===============================
  docs:
  pj:
    directory: ${DOCS_PJ_DIRECTORY:${user.home}/PIECES_JOINTES}


eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true

docs:
  pj:
    directory: ./uploads/pj