server:
  port: 8081

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5433/qualiapproche_user
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/quali-approche
  mail:
    host: smtp.gmail.com
    port: 587
    username: tachquali@gmail.com
    password: qpkcnamwhjfkundy
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

frontend:
  url: http://localhost:4200

keycloak:
  realm: quali
  serverUrl: http://localhost:8080
  clientId: quali-approche
  clientSecret: EGBtXZ6hO13LHY8BfFwjkUgdINNtAXeu
  issuerUri: http://localhost:8080/realms/quali
  tokenUri: http://localhost:8080/realms/quali/protocol/openid-connect/token
  adminUsername: admin
  adminPassword: admin
