server:
  port: 8085

spring:
  application:
    name: evaluation-service
  datasource:
    url: ${DB_URL_EVALUATION:jdbc:postgresql://localhost:5432/bd_quali_sira_evaluation}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KC_ISSUER_URI:http://localhost:8080/realms/quali}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true
