server:
  port: 8089

spring:
  application:
    name: support-service
  datasource:
    url: ${DB_URL_SUPPORT:jdbc:postgresql://localhost:5433/bd_quali_sira_support}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KC_ISSUER_URI:http://localhost:8080/realms/quali-approche}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true