--
-- support-service — schéma initial, relevé du schéma en service au 7 août 2026.
--
-- Module documentaire : documents, versions, demandes, accès, piste d'audit.
--
-- Ce script est le POINT DE DÉPART de l'historique de migration : il décrit le schéma tel que
-- « ddl-auto: update » l'avait construit. Une base déjà en service est marquée « v1 » sans que ce
-- script y soit rejoué (baseline-on-migrate) ; une base vide le reçoit intégralement. Les deux
-- suivent ensuite la même suite de migrations, ce qui est tout l'objet de Flyway.
--
-- NE JAMAIS MODIFIER un script déjà appliqué : Flyway en vérifie l'empreinte et refuserait de
-- démarrer. Toute correction du schéma passe par un nouveau V<n+1>__....sql.
--

--
--

SET default_table_access_method = heap;

--
-- Name: qms_audit_logs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.qms_audit_logs (
    id bigint NOT NULL,
    action character varying(255) NOT NULL,
    details character varying(255),
    document_number character varying(255),
    "timestamp" timestamp(6) without time zone NOT NULL,
    username character varying(255) NOT NULL
);

--
-- Name: qms_audit_logs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.qms_audit_logs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.qms_audit_logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: qms_demandes_document; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.qms_demandes_document (
    id uuid NOT NULL,
    created_at timestamp(6) without time zone,
    created_by_id character varying(255),
    current_user_email character varying(255),
    current_user_structure character varying(255),
    current_user_full_name character varying(255),
    direction_id uuid,
    update_at timestamp(6) without time zone,
    update_by_id character varying(255),
    current_etape character varying(255),
    date_decision timestamp(6) without time zone,
    date_execution timestamp(6) without time zone,
    demandeur_id character varying(255),
    demandeur_nom character varying(255),
    description character varying(4000),
    document_id uuid NOT NULL,
    document_number character varying(255),
    document_titre character varying(255),
    etat character varying(255) NOT NULL,
    motif_decision character varying(2000),
    objectif character varying(1000) NOT NULL,
    piece_jointe_nom character varying(255),
    piece_jointe_object_name character varying(255),
    structure_id character varying(255),
    structure_libelle character varying(255),
    type character varying(255) NOT NULL,
    workflow_id uuid,
    CONSTRAINT qms_demandes_document_etat_check CHECK (((etat)::text = ANY ((ARRAY['EN_COURS'::character varying, 'ACCEPTEE'::character varying, 'REFUSEE'::character varying, 'EXECUTEE'::character varying])::text[]))),
    CONSTRAINT qms_demandes_document_type_check CHECK (((type)::text = ANY ((ARRAY['MODIFICATION'::character varying, 'SUPPRESSION'::character varying])::text[])))
);

--
-- Name: qms_document_structure_access; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.qms_document_structure_access (
    id uuid NOT NULL,
    etape_code character varying(255),
    shared_at timestamp(6) without time zone,
    shared_by_full_name character varying(255),
    shared_by_user_id character varying(255),
    structure_id character varying(255) NOT NULL,
    structure_libelle character varying(255),
    document_id uuid NOT NULL
);

--
-- Name: qms_document_types; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.qms_document_types (
    id uuid NOT NULL,
    created_at timestamp(6) without time zone,
    created_by_id character varying(255),
    current_user_email character varying(255),
    current_user_structure character varying(255),
    current_user_full_name character varying(255),
    direction_id uuid,
    update_at timestamp(6) without time zone,
    update_by_id character varying(255),
    code character varying(255) NOT NULL,
    folder_name character varying(255) NOT NULL,
    libelle character varying(255) NOT NULL
);

--
-- Name: qms_document_user_access; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.qms_document_user_access (
    id uuid NOT NULL,
    role character varying(255) NOT NULL,
    user_email character varying(255),
    user_full_name character varying(255),
    user_id character varying(255) NOT NULL,
    document_id uuid NOT NULL
);

--
-- Name: qms_document_versions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.qms_document_versions (
    id bigint NOT NULL,
    comment character varying(255),
    created_by character varying(255) NOT NULL,
    date_creation timestamp(6) without time zone NOT NULL,
    file_hash character varying(255),
    file_size bigint,
    object_name character varying(255) NOT NULL,
    original_filename character varying(255),
    version_label character varying(255) NOT NULL,
    document_id uuid NOT NULL
);

--
-- Name: qms_document_versions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.qms_document_versions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.qms_document_versions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: qms_documents; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.qms_documents (
    id uuid NOT NULL,
    created_at timestamp(6) without time zone,
    created_by_id character varying(255),
    current_user_email character varying(255),
    current_user_structure character varying(255),
    current_user_full_name character varying(255),
    direction_id uuid,
    update_at timestamp(6) without time zone,
    update_by_id character varying(255),
    alerte_envoyee character varying(255),
    archived boolean NOT NULL,
    confidentiel boolean NOT NULL,
    current_etape character varying(255),
    date_proch_revision timestamp(6) without time zone,
    date_publication timestamp(6) without time zone,
    date_vigueur timestamp(6) without time zone,
    description character varying(255),
    document_externe boolean NOT NULL,
    document_number character varying(255) NOT NULL,
    document_type character varying(255) NOT NULL,
    domaine character varying(255),
    domaine_id character varying(255),
    en_retard_revision boolean NOT NULL,
    es_traiter boolean NOT NULL,
    last_modified_by character varying(255),
    last_modified_reason character varying(255),
    nc_reference character varying(255),
    niveau_confidentialite_id character varying(255),
    niveau_confidentialite_libelle character varying(255),
    numero_version integer NOT NULL,
    obsolete boolean NOT NULL,
    periodicite_mois integer,
    priorite_id character varying(255),
    priorite_libelle character varying(255),
    processus_dest_id character varying(255),
    processus_dest_libelle character varying(255),
    redacteur character varying(255) NOT NULL,
    reference character varying(255),
    reference_officielle character varying(255),
    service_id character varying(255) NOT NULL,
    service_libelle character varying(255),
    service_sigle character varying(255),
    statut_legal character varying(255),
    titre character varying(255) NOT NULL,
    version bigint,
    workflow_id uuid
);

--
-- Name: qms_pieces_etape; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.qms_pieces_etape (
    id uuid NOT NULL,
    created_at timestamp(6) without time zone,
    created_by_id character varying(255),
    current_user_email character varying(255),
    current_user_structure character varying(255),
    current_user_full_name character varying(255),
    direction_id uuid,
    update_at timestamp(6) without time zone,
    update_by_id character varying(255),
    dossier_id uuid NOT NULL,
    famille character varying(30) NOT NULL,
    nom character varying(255) NOT NULL,
    reference character varying(512) NOT NULL,
    taille bigint NOT NULL,
    type character varying(150)
);

--
-- Name: qms_workflow_step_templates; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.qms_workflow_step_templates (
    id uuid NOT NULL,
    created_at timestamp(6) without time zone,
    created_by_id character varying(255),
    current_user_email character varying(255),
    current_user_structure character varying(255),
    current_user_full_name character varying(255),
    direction_id uuid,
    update_at timestamp(6) without time zone,
    update_by_id character varying(255),
    code character varying(255) NOT NULL,
    description character varying(255),
    nom_etape character varying(255) NOT NULL,
    responsable_role character varying(255) NOT NULL
);

--
-- Name: qms_audit_logs qms_audit_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.qms_audit_logs
    ADD CONSTRAINT qms_audit_logs_pkey PRIMARY KEY (id);

--
-- Name: qms_demandes_document qms_demandes_document_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.qms_demandes_document
    ADD CONSTRAINT qms_demandes_document_pkey PRIMARY KEY (id);

--
-- Name: qms_document_structure_access qms_document_structure_access_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.qms_document_structure_access
    ADD CONSTRAINT qms_document_structure_access_pkey PRIMARY KEY (id);

--
-- Name: qms_document_types qms_document_types_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.qms_document_types
    ADD CONSTRAINT qms_document_types_pkey PRIMARY KEY (id);

--
-- Name: qms_document_user_access qms_document_user_access_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.qms_document_user_access
    ADD CONSTRAINT qms_document_user_access_pkey PRIMARY KEY (id);

--
-- Name: qms_document_versions qms_document_versions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.qms_document_versions
    ADD CONSTRAINT qms_document_versions_pkey PRIMARY KEY (id);

--
-- Name: qms_documents qms_documents_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.qms_documents
    ADD CONSTRAINT qms_documents_pkey PRIMARY KEY (id);

--
-- Name: qms_pieces_etape qms_pieces_etape_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.qms_pieces_etape
    ADD CONSTRAINT qms_pieces_etape_pkey PRIMARY KEY (id);

--
-- Name: qms_workflow_step_templates qms_workflow_step_templates_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.qms_workflow_step_templates
    ADD CONSTRAINT qms_workflow_step_templates_pkey PRIMARY KEY (id);

--
-- Name: qms_document_structure_access uk_document_structure; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.qms_document_structure_access
    ADD CONSTRAINT uk_document_structure UNIQUE (document_id, structure_id);

--
-- Name: qms_workflow_step_templates uk_step_template_code; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.qms_workflow_step_templates
    ADD CONSTRAINT uk_step_template_code UNIQUE (code);

--
-- Name: qms_pieces_etape ukjw6galv089yhyjkqhiy1eeb1c; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.qms_pieces_etape
    ADD CONSTRAINT ukjw6galv089yhyjkqhiy1eeb1c UNIQUE (reference);

--
-- Name: qms_documents ukpa5sg88srrfutqt2x74ln78qj; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.qms_documents
    ADD CONSTRAINT ukpa5sg88srrfutqt2x74ln78qj UNIQUE (document_number);

--
-- Name: qms_document_types uktdf210qog6ow68s5xt4jfyxb9; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.qms_document_types
    ADD CONSTRAINT uktdf210qog6ow68s5xt4jfyxb9 UNIQUE (code);

--
-- Name: idx_piece_etape_dossier; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_piece_etape_dossier ON public.qms_pieces_etape USING btree (famille, dossier_id);

--
-- Name: qms_document_versions fk2qoma9hehan52xlob120wudm6; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.qms_document_versions
    ADD CONSTRAINT fk2qoma9hehan52xlob120wudm6 FOREIGN KEY (document_id) REFERENCES public.qms_documents(id);

--
-- Name: qms_document_structure_access fk32wx33o2rn4jmyvxyhxlymnds; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.qms_document_structure_access
    ADD CONSTRAINT fk32wx33o2rn4jmyvxyhxlymnds FOREIGN KEY (document_id) REFERENCES public.qms_documents(id);

--
-- Name: qms_document_user_access fk83kx8ohakld5el4xlqwvbwi7k; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.qms_document_user_access
    ADD CONSTRAINT fk83kx8ohakld5el4xlqwvbwi7k FOREIGN KEY (document_id) REFERENCES public.qms_documents(id);

--
--
