name: Deploy API Gateway

on:
  push:
    branches:
      - develop

    paths:
      - 'api-gateway/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build api-gateway
        run: |
          cd api-gateway
          mvn clean install -DskipTests

      - name: Trigger Coolify Deployment
        run: |
          echo "Calling Coolify webhook..."
          
          response=$(curl -s -o response.txt -w "%{http_code}" \
          -X GET "${{ secrets.API_GATEWAY_WEBHOOK }}")

          echo "HTTP Status: $response"

          echo "Response:"
          cat response.txt

          if [ "$response" -ne 200 ]; then
            echo "Deployment webhook failed!"
            exit 1
          fi

          echo "Deployment triggered successfully!"