name: Deploy Frontend to Coolify
on:
  push:
    branches: [ develop ]

jobs:
  trigger-coolify:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Coolify Server
        run: |
          echo "🚀 Sending deploy request to Coolify..."
          curl -i "http://144.126.135.120:8000/api/v1/deploy?uuid=br35fnx2p51sj0lksong6cgx&force=false"
