name: Deploy Frontend

on:
  push:
    branches:
      - develop

    paths:
      - 'FrontQualiApproche/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          cd FrontQualiApproche
          npm install

      - name: Build Angular
        run: |
          cd FrontQualiApproche
          npm run build --configuration production

      - name: Trigger Coolify Deployment
        run: |
          echo "Calling Coolify webhook..."
          
          response=$(curl -s -o response.txt -w "%{http_code}" \
          -X GET "${{ secrets.FRONTEND_WEBHOOK }}")

          echo "HTTP Status: $response"

          echo "Response:"
          cat response.txt

          if [ "$response" -ne 200 ]; then
            echo "Deployment webhook failed!"
            exit 1
          fi

          echo "Deployment triggered successfully!"